# Build stage
FROM golang:1.18-alpine3.15
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -o /bin/app ./tools/turn

# Run stage
FROM alpine:3.15
WORKDIR /src
COPY --from=builder /bin/app /bin/app

ENTRYPOINT [ "/bin/app" ]